# Generated by Django 6.0.7 on 2026-08-14 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, default='Sector 4, City Center', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='upvote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Damage'), ('water', 'Water Logging'), ('drainage', 'Drainage / Sewage'), ('lighting', 'Street Lighting'), ('garbage', 'Garbage Dump'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=28.6139, max_digits=9),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=77.209, max_digits=9),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
